-- MySQL Script generated by MySQL Workbench
-- Mon Sep  9 15:24:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetodiariotarde
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetodiario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetodiario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetodiario` ;
USE `projetodiario` ;

-- -----------------------------------------------------
-- Table `projetodiario`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetodiario`.`aluno` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `ra` CHAR(8) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`ra` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `projetodiario`.`diariobordo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetodiario`.`diariobordo` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `texto` TEXT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `fk_aluno_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_diariobordo` (`fk_aluno_id` ASC) VISIBLE,
  CONSTRAINT `FK_diariobordo`
    FOREIGN KEY (`fk_aluno_id`)
    REFERENCES `projetodiario`.`aluno` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `projetodiario`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetodiario`.`avaliacao` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nota1` INT NULL DEFAULT NULL,
  `nota2` INT NULL DEFAULT NULL,
  `nota3` INT NULL DEFAULT NULL,
  `nota4` INT NULL DEFAULT NULL,
  `fk_aluno_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_avaliacao` (`fk_aluno_id` ASC) VISIBLE,
  CONSTRAINT `FK_avaliacao`
    FOREIGN KEY (`fk_aluno_id`)
    REFERENCES `projetodiario`.`aluno` (`id`)
    ON DELETE CASCADE);


-- -----------------------------------------------------
-- Table `projetodiario`.`instrutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetodiario`.`instrutor` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`user_name` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
